//! Part 9 of the sensor-width table of `colmap/sensor/specs.cc` (makes
//! "lge" to "yuneec"). GENERATED by `scripts/generate-camera-specs.py`
//! from the C++ reference; do not edit by hand. Chained by `specs/mod.rs`.

use super::CameraMakeSpecs;

pub(super) const MAKES: &[CameraMakeSpecs] = &[
    CameraMakeSpecs {
        make: "lge",
        models: &[("nexus5", 4.5400)],
    },
    CameraMakeSpecs {
        make: "mantis",
        models: &[("i23", 45.0000)],
    },
    CameraMakeSpecs {
        make: "mobius",
        models: &[("actioncam", 2.1000)],
    },
    CameraMakeSpecs {
        make: "oneplu",
        models: &[("a000", 4.8000)],
    },
    CameraMakeSpecs {
        make: "phantom",
        models: &[("visionfc200", 6.1700)],
    },
    CameraMakeSpecs {
        make: "phaseone",
        models: &[("ixmrs100f", 53.4000)],
    },
    CameraMakeSpecs {
        make: "skydio",
        models: &[("2", 5.4760)],
    },
    CameraMakeSpecs {
        make: "teracube",
        models: &[("teracubeone", 4.7100)],
    },
    CameraMakeSpecs {
        make: "yuneec",
        models: &[("e90", 13.2000)],
    },
];
