#!/usr/bin/env python3
# Generates colmap-rust/src/sensor/specs/data*.rs from COLMAP's sensor/specs.cc (the camera
# sensor-width database, ~4,400 entries). Port of colmap-sharp's
# scripts/generate-camera-specs.py. The data is copied verbatim - make, model and sensor width
# in the order specs.cc lists them - so regenerating after a REFERENCE bump is the whole port.
# The output is split into modules at make boundaries so no file exceeds the
# 800-non-empty-line limit (CLAUDE.md); colmap-rust/src/sensor/specs/mod.rs chains them.
#
# Usage: scripts/fetch-reference.sh && python3 scripts/generate-camera-specs.py && cargo fmt
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "cpp-reference/src/colmap/sensor/specs.cc"
OUT_DIR = ROOT / "colmap-rust/src/sensor/specs"
MAX_LINES_PER_FILE = 700

MAKE_RE = re.compile(r'auto& make_specs = specs\["([^"\\]*)"\];')
ENTRY_RE = re.compile(r'make_specs\.emplace_back\("([^"\\]*)", ([0-9.]+)f\);')


def parse(text):
    makes = []
    for line in text.splitlines():
        make = MAKE_RE.search(line)
        if make:
            makes.append((make.group(1), []))
            continue
        entry = ENTRY_RE.search(line)
        if entry:
            makes[-1][1].append((entry.group(1), entry.group(2)))
        elif "emplace_back" in line:
            sys.exit(f"unrecognized entry line: {line.strip()}")
    names = [name for name, _ in makes]
    if len(names) != len(set(names)):
        sys.exit("a make appears twice; InitializeCameraSpecs would merge it")
    return makes


def chunk(makes):
    chunks, current, size = [], [], 0
    for make in makes:
        make_size = len(make[1]) + 5
        if current and size + make_size > MAX_LINES_PER_FILE:
            chunks.append(current)
            current, size = [], 0
        current.append(make)
        size += make_size
    if current:
        chunks.append(current)
    return chunks


def write_chunk(index, makes):
    lines = [
        f"//! Part {index} of the sensor-width table of `colmap/sensor/specs.cc` (makes",
        f"//! \"{makes[0][0]}\" to \"{makes[-1][0]}\"). GENERATED by `scripts/generate-camera-specs.py`",
        "//! from the C++ reference; do not edit by hand. Chained by `specs/mod.rs`.",
        "",
        "use super::CameraMakeSpecs;",
        "",
        "pub(super) const MAKES: &[CameraMakeSpecs] = &[",
    ]
    for make, models in makes:
        lines.append("    CameraMakeSpecs {")
        lines.append(f"        make: \"{make}\",")
        lines.append("        models: &[")
        for model, width in models:
            lines.append(f"            (\"{model}\", {width}),")
        lines.append("        ],")
        lines.append("    },")
    lines += ["];", ""]
    (OUT_DIR / f"data{index}.rs").write_text("\n".join(lines))


def main():
    makes = parse(SOURCE.read_text())
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for old in OUT_DIR.glob("data*.rs"):
        old.unlink()
    chunks = chunk(makes)
    for index, part in enumerate(chunks, start=1):
        write_chunk(index, part)
    print(f"{len(makes)} makes, {sum(len(m) for _, m in makes)} models, {len(chunks)} files")
    print("modules: " + ", ".join(f"data{i}" for i in range(1, len(chunks) + 1)))


if __name__ == "__main__":
    main()
